### ISSUE TITLE
I have the following problems when downloading it.

### ISSUE THREAD

**Issue by ct-hub** [JorgeFCS/Image-fusion-GAN#1]
I have the following problems when downloading it.
Error downloading object: Sample_model/DISC1.h5 (1bb9c1b): Smudge error: Error downloading Sample_model/DISC1.h5 (1bb9c1b3896a80d46bc91ad05f24ac4b1111b658c63d1f4cf2c6d6bdae29ed47): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
How can I get it？Thank you very much。

**Comment by JorgeFCS** [comment]
Hi! Thanks for letting me know. I have checked and the issue has to do with Git LFS free storage quota. Unfortunately, the only fix for freeing remote storage space in Git LFS with Github appears to be deleting the entire repository.

I will do this on Monday, and make a new repository with the same content and name. This time, I will provide a Google Drive link to download the H5 files and update the README file accordingly.

**Comment by ct-hub** [comment]
OK, thank you very much for your help.
