### ISSUE TITLE
Question about H5

### ISSUE THREAD

**Issue by ct-hub** [JorgeFCS/Image-fusion-GAN#3]
Hello, I downloaded your H5 file. Is it the weight after transfer and learning? Or is it just the weight of gamma=1 training that hasn't been transferred yet?

**Comment by JorgeFCS** [comment]
Hi! The weights are of the model pre-trained on the RGB-NIR dataset **only**, with gamma=1.  In the _Sample_model_ directory you can find a README file with details on the training parameters.
